import { useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react";
import { motion } from "framer-motion";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { loadDashboard } from "./api";
import type { DashboardData, Language, Manifest, SectionKey, SeriesRow } from "./types";

type Tech = { key: string; en: string; es: string; color: string; family: "renewable" | "zero" | "fossil" };
type Preset = "all" | "renewable" | "low" | "fossil" | "custom";
type InterconnectorMode = "split" | "net";

const TECH: Record<string, Tech> = {
  "Hidráulica": { key: "hydro", en: "Hydro", es: "Hidráulica", color: "#2E7DD7", family: "renewable" },
  "Eólica": { key: "wind", en: "Wind", es: "Eólica", color: "#20B785", family: "renewable" },
  "Solar fotovoltaica": { key: "solar_pv", en: "Solar PV", es: "Solar fotovoltaica", color: "#F0C94A", family: "renewable" },
  "Solar térmica": { key: "solar_thermal", en: "Solar thermal", es: "Solar térmica", color: "#E58A35", family: "renewable" },
  "Otras renovables": { key: "other_renewables", en: "Other renewables", es: "Otras renovables", color: "#89C05A", family: "renewable" },
  "Residuos renovables": { key: "renewable_waste", en: "Renewable waste", es: "Residuos renovables", color: "#68A95B", family: "renewable" },
  "Hidroeólica": { key: "hydro_wind", en: "Hydro-wind", es: "Hidroeólica", color: "#47B8B0", family: "renewable" },
  Nuclear: { key: "nuclear", en: "Nuclear", es: "Nuclear", color: "#9F85D8", family: "zero" },
  "Ciclo combinado": { key: "combined_cycle", en: "Combined cycle", es: "Ciclo combinado", color: "#E56857", family: "fossil" },
  "Cogeneración": { key: "cogeneration", en: "Cogeneration", es: "Cogeneración", color: "#C98772", family: "fossil" },
  "Carbón": { key: "coal", en: "Coal", es: "Carbón", color: "#7C8991", family: "fossil" },
  "Fuel + Gas": { key: "fuel_gas", en: "Fuel + gas", es: "Fuel + gas", color: "#A67363", family: "fossil" },
  "Motores diésel": { key: "diesel", en: "Diesel engines", es: "Motores diésel", color: "#9A6152", family: "fossil" },
  "Turbina de gas": { key: "gas_turbine", en: "Gas turbine", es: "Turbina de gas", color: "#B57861", family: "fossil" },
  "Turbina de vapor": { key: "steam_turbine", en: "Steam turbine", es: "Turbina de vapor", color: "#8E655A", family: "fossil" },
  "Residuos no renovables": { key: "nonrenewable_waste", en: "Non-renewable waste", es: "Residuos no renovables", color: "#69777D", family: "fossil" },
};

const STORAGE: Record<string, { key: string; en: string; es: string; color: string }> = {
  "Turbinación bombeo": { key: "pumped_storage", en: "Pumped storage", es: "Turbinación de bombeo", color: "#2E7DD7" },
  "Batería": { key: "battery", en: "Battery", es: "Batería", color: "#9EF01A" },
};

const BORDER = {
  France: { en: "France", es: "Francia", color: "#2E7DD7" },
  Portugal: { en: "Portugal", es: "Portugal", color: "#20B785" },
  Morocco: { en: "Morocco", es: "Marruecos", color: "#E58A35" },
  Andorra: { en: "Andorra", es: "Andorra", color: "#9F85D8" },
} as const;

const C = {
  en: {
    strap: "Spain's electricity system", generation: "Generation", interconnectors: "Interconnectors", coverage: "Coverage", marginal: "Marginal price", system: "System", headingLabel: "Spain / electricity",
    generationTitle: "How Spain generates electricity", generationCopy: "Generation by technology. National system.", mix: "Generation mix — month by month", rolling: "12-month source trend", balance: "Generation and demand", shape: "The shape of a day",
    interTitle: "Cross-border electricity flows", interCopy: "Monthly physical exchanges. Imports are above zero; exports are below it.", bothFlows: "Imports + exports", netFlows: "Net by country", selectedBorders: "Selected countries", net: "net",
    coverageTitle: "When selected sources cover demand", coverageCopy: "Choose technologies, a demand threshold and a period to measure how often they supplied that share of demand.", coverageResult: "Hourly coverage analysis", threshold: "Demand threshold", selectedSources: "Selected technologies",
    marginalTitle: "What shaped the electricity price", marginalCopy: "See which technology most often set the market price until 18 March 2025. After that date, OMIE prices remain visible, but a reliable technology label is no longer available.",
    systemTitle: "Capacity, storage and carbon context", systemCopy: "Track the generation fleet, emerging storage capacity and the carbon profile of electricity production.", installed: "Installed capacity — month by month", storage: "Storage capacity", carbon: "Generation associated with CO₂-eq emissions", context: "OMIE price context", archive: "Marginal price-setting technology",
    carbonNote: "This is the monthly share of electricity generated by technologies that REE classifies as having associated CO₂-equivalent emissions. It is a share of generation, not an emissions-intensity measure in gCO₂/kWh.",
    all: "All", renewables: "Renewables", lowCarbon: "Low carbon", fossil: "Fossil", from: "From", to: "To", sources: "Sources", geography: "Geography", national: "Spain · national system", imports: "imports", exports: "exports", contextOnly: "Context only after 18 Mar 2025", unavailable: "Not available",
    hourlyNeeded: "Hourly technology data needs e·sios access", hourlyDetail: "The public REData generation and demand widgets return errors at hourly granularity. No monthly proxy is used for an hourly calculation.", noRows: "No validated observations are available for this module yet.", error: "Public data could not be loaded.", retry: "Retry",
  },
  es: {
    strap: "El sistema eléctrico español", generation: "Generación", interconnectors: "Interconexiones", coverage: "Cobertura", marginal: "Precio marginal", system: "Sistema", headingLabel: "España / electricidad",
    generationTitle: "Cómo genera electricidad España", generationCopy: "Generación por tecnología. Sistema nacional.", mix: "Mix de generación — mes a mes", rolling: "Tendencia de fuentes a 12 meses", balance: "Generación y demanda", shape: "La forma de un día",
    interTitle: "Flujos eléctricos transfronterizos", interCopy: "Intercambios físicos mensuales. Las importaciones están sobre cero y las exportaciones, por debajo.", bothFlows: "Importaciones + exportaciones", netFlows: "Neto por país", selectedBorders: "Países elegidos", net: "neto",
    coverageTitle: "Cuándo cubren la demanda las fuentes elegidas", coverageCopy: "Elige tecnologías, un umbral de demanda y un periodo para medir con qué frecuencia aportaron esa proporción de la demanda.", coverageResult: "Análisis horario de cobertura", threshold: "Umbral de demanda", selectedSources: "Tecnologías elegidas",
    marginalTitle: "Qué determinó el precio de la electricidad", marginalCopy: "Consulta qué tecnología fijó con más frecuencia el precio hasta el 18 de marzo de 2025. Después, se mantienen los precios OMIE, pero ya no existe una etiqueta tecnológica fiable.",
    systemTitle: "Contexto de capacidad, almacenamiento y carbono", systemCopy: "Sigue la evolución del parque generador, la nueva capacidad de almacenamiento y el perfil de carbono de la producción eléctrica.", installed: "Potencia instalada — mes a mes", storage: "Capacidad de almacenamiento", carbon: "Generación asociada a emisiones de CO₂-eq", context: "Contexto de precio OMIE", archive: "Tecnología que fijó el precio marginal",
    carbonNote: "Es la proporción mensual de electricidad producida por tecnologías que REE clasifica como asociadas a emisiones de CO₂ equivalente. Es una cuota de generación, no una medida de intensidad en gCO₂/kWh.",
    all: "Todas", renewables: "Renovables", lowCarbon: "Bajas en carbono", fossil: "Fósiles", from: "Desde", to: "Hasta", sources: "Fuentes", geography: "Ámbito", national: "España · sistema nacional", imports: "importaciones", exports: "exportaciones", contextOnly: "Solo contexto desde el 18 mar 2025", unavailable: "No disponible",
    hourlyNeeded: "Los datos horarios por tecnología necesitan acceso a e·sios", hourlyDetail: "Los indicadores públicos de generación y demanda de REData devuelven errores a escala horaria. No se utiliza una aproximación mensual para un cálculo horario.", noRows: "Todavía no hay observaciones validadas para este módulo.", error: "No se pudieron cargar los datos públicos.", retry: "Reintentar",
  },
} as const;

const allTech = Object.values(TECH);
const techByKey = new Map(allTech.map((tech) => [tech.key, tech]));
const getLang = (): Language => new URLSearchParams(location.search).get("lang") === "es" ? "es" : "en";
const locale = (lang: Language) => lang === "es" ? "es-ES" : "en-GB";
const formatInteger = (value: number, lang: Language) => {
  const rounded = Math.round(value); const formatted = new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 0, useGrouping: true }).format(rounded);
  if (Math.abs(rounded) >= 1000 && Math.abs(rounded) < 10000 && !/[.,\s]/.test(formatted)) { const digits = String(Math.abs(rounded)); return `${rounded < 0 ? "-" : ""}${digits.slice(0, -3)}${lang === "es" ? "." : ","}${digits.slice(-3)}`; }
  return formatted;
};
const formatPrice = (value: number, lang: Language) => new Intl.NumberFormat(locale(lang), { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
const compact = (value: number, lang: Language) => new Intl.NumberFormat(locale(lang), { notation: "compact", maximumFractionDigits: 1 }).format(value);
const month = (value: string, lang: Language) => new Intl.DateTimeFormat(locale(lang), { month: "short", year: "2-digit", timeZone: "UTC" }).format(new Date(`${value}-01T00:00:00Z`));

function reshape(rows: SeriesRow[], dictionary: Record<string, { key: string }>) {
  const result = new Map<string, Record<string, string | number>>();
  rows.forEach((row) => {
    const meta = dictionary[row.series];
    if (!meta) return;
    const item = result.get(row.period) ?? { period: row.period, total: 0 };
    item[meta.key] = row.value; item.total = Number(item.total) + row.value; result.set(row.period, item);
  });
  return [...result.values()].sort((a, b) => String(a.period).localeCompare(String(b.period)));
}

function rolling(rows: Array<Record<string, string | number>>, keys: string[]) {
  return rows.map((row, index) => {
    const window = rows.slice(Math.max(0, index - 11), index + 1);
    const out: Record<string, string | number> = { period: row.period };
    keys.forEach((key) => { out[key] = window.reduce((sum, item) => sum + Number(item[key] ?? 0), 0) / window.length; });
    return out;
  });
}

function Panel({ code, title, children }: { code: string; title: string; children: ReactNode }) {
  return <motion.section className="panel" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><header><span>{code}</span><h2>{title}</h2></header>{children}</motion.section>;
}
function Empty({ title, copy }: { title: string; copy: string }) { return <div className="empty"><b>!</b><div><strong>{title}</strong><p>{copy}</p></div></div>; }
function TechnologyToggles({ active, lang, toggle, label }: { active: Set<string>; lang: Language; toggle: (key: string) => void; label: string }) {
  return <div className="technology-filter"><span>{label}</span><div>{allTech.map((tech) => <button key={tech.key} className={active.has(tech.key) ? "active" : ""} aria-pressed={active.has(tech.key)} onClick={() => toggle(tech.key)}><i style={{ "--series": tech.color } as CSSProperties}/>{tech[lang]}</button>)}</div></div>;
}

export default function App() {
  const [lang, setLang] = useState<Language>(getLang); const [section, setSection] = useState<SectionKey>("generation");
  const [data, setData] = useState<DashboardData | null>(null); const [manifest, setManifest] = useState<Manifest | null>(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0);
  const [preset, setPreset] = useState<Preset>("all"); const [enabled, setEnabled] = useState(() => new Set(allTech.map((tech) => tech.key)));
  const [from, setFrom] = useState("2019-01"); const [to, setTo] = useState("2026-12");
  const [systemFrom, setSystemFrom] = useState("2019-01"); const [systemTo, setSystemTo] = useState("2026-12");
  const [interFrom, setInterFrom] = useState("2019-01"); const [interTo, setInterTo] = useState("2026-12");
  const [interMode, setInterMode] = useState<InterconnectorMode>("split"); const [enabledBorders, setEnabledBorders] = useState(() => new Set<keyof typeof BORDER>(Object.keys(BORDER) as Array<keyof typeof BORDER>));
  const [coverageFrom, setCoverageFrom] = useState("2025-01"); const [coverageTo, setCoverageTo] = useState("2026-12"); const [coverageThreshold, setCoverageThreshold] = useState(50);
  const [coverageTech, setCoverageTech] = useState(() => new Set(["solar_pv"]));
  const t = C[lang];

  useEffect(() => { document.documentElement.lang = lang; }, [lang]);
  useEffect(() => { loadDashboard().then(({ dashboard, manifest: loaded }) => { const start = loaded.coverage.monthly_start ?? "2019-01"; const end = loaded.coverage.monthly_end ?? "2026-12"; setData(dashboard); setManifest(loaded); setFrom(start); setTo(end); setSystemFrom(start); setSystemTo(end); setInterFrom(start); setInterTo(end); setCoverageTo(end); }).catch((reason) => setError(String(reason))); }, [attempt]);
  const setLanguage = (next: Language) => { setLang(next); const url = new URL(location.href); next === "es" ? url.searchParams.set("lang", "es") : url.searchParams.delete("lang"); history.replaceState({}, "", url); document.documentElement.lang = next; };
  const applyPreset = (next: Exclude<Preset, "custom">) => { setPreset(next); setEnabled(new Set(allTech.filter((tech) => next === "all" || (next === "low" ? tech.family !== "fossil" : tech.family === next)).map((tech) => tech.key))); };
  const toggleTechnology = (key: string) => { setPreset("custom"); setEnabled((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; }); };
  const toggleCoverage = (key: string) => setCoverageTech((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; });
  const toggleBorder = (key: keyof typeof BORDER) => setEnabledBorders((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; });

  const activeTech = allTech.filter((tech) => enabled.has(tech.key)); const activeKeys = activeTech.map((tech) => tech.key);
  const allGeneration = useMemo(() => data ? reshape(data.generation, TECH) : [], [data]);
  const generation = useMemo(() => allGeneration.filter((row) => String(row.period) >= from && String(row.period) <= to), [allGeneration, from, to]);
  const trend = useMemo(() => rolling(allGeneration, activeKeys).filter((row) => String(row.period) >= from && String(row.period) <= to), [allGeneration, activeKeys.join("|"), from, to]);
  const demandMap = new Map((data?.demand ?? []).filter((row) => row.series === "Demanda").map((row) => [row.period, row.value]));
  const balance = generation.map((row) => ({ period: row.period, generation: row.total, demand: demandMap.get(String(row.period)) }));
  const capacity = useMemo(() => data ? reshape(data.capacity, TECH).filter((row) => String(row.period) >= systemFrom && String(row.period) <= systemTo) : [], [data, systemFrom, systemTo]);
  const storageCapacity = useMemo(() => data ? reshape(data.storage_capacity ?? [], STORAGE).filter((row) => String(row.period) >= systemFrom && String(row.period) <= systemTo) : [], [data, systemFrom, systemTo]);
  const carbon = (data?.emissions_context ?? []).filter((row) => row.series === "Con emisiones de CO2 eq." && row.period >= systemFrom && row.period <= systemTo);
  const exchangeData = useMemo(() => { const byPeriod = new Map<string, Record<string, string | number>>(); (data?.exchanges ?? []).filter((row) => row.period >= interFrom && row.period <= interTo).forEach((row) => { const item = byPeriod.get(row.period) ?? { period: row.period }; item[`${row.country}_${row.direction}`] = row.value_gwh; byPeriod.set(row.period, item); }); return [...byPeriod.values()].map((item) => { Object.keys(BORDER).forEach((country) => { item[`${country}_net`] = Number(item[`${country}_import`] ?? 0) + Number(item[`${country}_export`] ?? 0); }); return item; }).sort((a, b) => String(a.period).localeCompare(String(b.period))); }, [data, interFrom, interTo]);
  const activeBorders = (Object.entries(BORDER) as Array<[keyof typeof BORDER, (typeof BORDER)[keyof typeof BORDER]]>).filter(([country]) => enabledBorders.has(country));

  const title: Record<SectionKey, [string, string]> = { generation: [t.generationTitle, t.generationCopy], interconnectors: [t.interTitle, t.interCopy], coverage: [t.coverageTitle, t.coverageCopy], system: [t.systemTitle, t.systemCopy], marginal: [t.marginalTitle, t.marginalCopy] };
  const nav: Array<[SectionKey, string]> = [["generation", t.generation], ["interconnectors", t.interconnectors], ["coverage", t.coverage], ["system", t.system], ["marginal", t.marginal]];
  const axis = { stroke: "#5D7481", fontSize: 11 }; const tip = { background: "#0C1824", border: "1px solid #29414E", borderRadius: 2, color: "#E8EEF0" };
  const technologyTooltip = (unit: "GWh" | "MW") => (value: number, name: string) => [`${formatInteger(Number(value), lang)} ${unit}`, techByKey.get(name)?.[lang] ?? name];

  if (error) return <main className="fatal"><p className="kicker">DATA / ERROR</p><h1>{t.error}</h1><code>{error}</code><button onClick={() => { setError(""); setAttempt((value) => value + 1); }}>{t.retry}</button></main>;
  if (!data || !manifest) return <main className="loading"><span/><p>LOADING PUBLIC DATA</p></main>;

  return <div className="shell"><header className="topbar"><a className="identity" href="https://danielalmazan.com"><strong>E-Spain</strong><span>{t.strap}</span></a><nav>{nav.map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}>{label}</button>)}</nav><div className="language"><button className={lang === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button><button className={lang === "es" ? "active" : ""} onClick={() => setLanguage("es")}>ES</button></div></header><main>
    <section className="section-head"><div><p className="kicker">{t.headingLabel}</p><h1>{section === "generation" && lang === "es" ? <>Cómo genera<br className="mobile-break"/> electricidad<br className="mobile-break"/> España</> : title[section][0]}</h1><p>{title[section][1]}</p></div><dl><div><dt>{t.geography}</dt><dd>{t.national}</dd></div></dl></section>

    {section === "generation" && <><div className="controls"><div className="segments">{(["all", "renewable", "low", "fossil"] as const).map((value) => <button key={value} className={preset === value ? "active" : ""} onClick={() => applyPreset(value)}>{value === "all" ? t.all : value === "renewable" ? t.renewables : value === "low" ? t.lowCarbon : t.fossil}</button>)}</div><label>{t.from}<input type="month" value={from} max={to} onChange={(event) => setFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={to} min={from} onChange={(event) => setTo(event.target.value)}/></label></div><TechnologyToggles active={enabled} lang={lang} toggle={toggleTechnology} label={t.selectedSources}/>
      <Panel code="01 / MIX" title={t.mix}><ResponsiveContainer width="100%" height={410}><AreaChart data={generation}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={68}/><Tooltip contentStyle={tip} formatter={technologyTooltip("GWh")} labelFormatter={(value) => month(value, lang)}/>{activeTech.map((tech) => <Area key={tech.key} dataKey={tech.key} name={tech.key} stackId="mix" stroke={tech.color} fill={tech.color} fillOpacity={0.88}/>)}</AreaChart></ResponsiveContainer></Panel>
      <div className="two"><Panel code="02 / TREND" title={t.rolling}><ResponsiveContainer width="100%" height={300}><LineChart data={trend}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={58}/><Tooltip contentStyle={tip} formatter={technologyTooltip("GWh")} labelFormatter={(value) => month(value, lang)}/>{activeTech.map((tech) => <Line key={tech.key} dataKey={tech.key} name={tech.key} stroke={tech.color} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></Panel><Panel code="03 / BALANCE" title={t.balance}><ResponsiveContainer width="100%" height={300}><LineChart data={balance}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={58}/><Tooltip contentStyle={tip} formatter={(value: number, name: string) => [`${formatInteger(Number(value), lang)} GWh`, name === "generation" ? t.generation : name === "demand" ? (lang === "es" ? "Demanda" : "Demand") : name]} labelFormatter={(value) => month(value, lang)}/><Line dataKey="generation" stroke="#9EF01A" dot={false} strokeWidth={2}/><Line dataKey="demand" stroke="#E8EEF0" dot={false}/></LineChart></ResponsiveContainer></Panel></div><Panel code="04 / HOURLY" title={t.shape}><Empty title={t.hourlyNeeded} copy={t.hourlyDetail}/></Panel></>}

    {section === "interconnectors" && <><div className="controls"><div className="segments"><button className={interMode === "split" ? "active" : ""} onClick={() => setInterMode("split")}>{t.bothFlows}</button><button className={interMode === "net" ? "active" : ""} onClick={() => setInterMode("net")}>{t.netFlows}</button></div><label>{t.from}<input type="month" value={interFrom} max={interTo} onChange={(event) => setInterFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={interTo} min={interFrom} onChange={(event) => setInterTo(event.target.value)}/></label></div><div className="technology-filter country-filter"><span>{t.selectedBorders}</span><div>{(Object.entries(BORDER) as Array<[keyof typeof BORDER, (typeof BORDER)[keyof typeof BORDER]]>).map(([country, meta]) => <button key={country} className={enabledBorders.has(country) ? "active" : ""} aria-pressed={enabledBorders.has(country)} onClick={() => toggleBorder(country)}><i style={{ "--series": meta.color } as CSSProperties}/>{meta[lang]}</button>)}</div></div><Panel code="01 / BORDERS" title={t.interTitle}>{exchangeData.length ? <ResponsiveContainer width="100%" height={430}><BarChart data={exchangeData} stackOffset="sign"><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={70}/><ReferenceLine y={0} stroke="#E8EEF0"/><Tooltip cursor={{ fill: "transparent" }} contentStyle={tip} labelStyle={{ color: "#E8EEF0" }} labelFormatter={(value) => month(value, lang)} formatter={(value: number, name: string) => { const [country, direction] = name.split("_"); const meta = BORDER[country as keyof typeof BORDER]; const amount = direction === "net" ? Number(value) : Math.abs(Number(value)); return [`${formatInteger(amount, lang)} GWh`, `${meta?.[lang] ?? country} · ${direction === "import" ? t.imports : direction === "export" ? t.exports : t.net}`]; }}/>{interMode === "split" ? activeBorders.flatMap(([country, meta]) => [<Bar key={`${country}_import`} dataKey={`${country}_import`} stackId="imports" fill={meta.color}/>, <Bar key={`${country}_export`} dataKey={`${country}_export`} stackId="exports" fill={meta.color} fillOpacity={0.62}/>]) : activeBorders.map(([country, meta]) => <Bar key={`${country}_net`} dataKey={`${country}_net`} stackId="net" fill={meta.color}/>)}</BarChart></ResponsiveContainer> : <Empty title={t.unavailable} copy={t.noRows}/>}</Panel></>}

    {section === "coverage" && <><div className="coverage-controls"><TechnologyToggles active={coverageTech} lang={lang} toggle={toggleCoverage} label={t.selectedSources}/><div className="coverage-parameters"><label>{t.threshold}<span><input type="range" min="1" max="100" value={coverageThreshold} onChange={(event) => setCoverageThreshold(Number(event.target.value))}/><output>{coverageThreshold}%</output></span></label><label>{t.from}<input type="month" value={coverageFrom} max={coverageTo} onChange={(event) => setCoverageFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={coverageTo} min={coverageFrom} onChange={(event) => setCoverageTo(event.target.value)}/></label></div></div><Panel code="01 / THRESHOLD" title={t.coverageResult}><Empty title={t.hourlyNeeded} copy={t.hourlyDetail}/></Panel></>}

    {section === "system" && <><div className="controls"><label>{t.from}<input type="month" value={systemFrom} max={systemTo} onChange={(event) => setSystemFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={systemTo} min={systemFrom} onChange={(event) => setSystemTo(event.target.value)}/></label></div><Panel code="01 / MW" title={t.installed}><ResponsiveContainer width="100%" height={420}><LineChart data={capacity}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={68}/><Tooltip contentStyle={tip} formatter={technologyTooltip("MW")} labelFormatter={(value) => month(value, lang)}/>{allTech.map((tech) => <Line key={tech.key} dataKey={tech.key} name={tech.key} stroke={tech.color} dot={false} strokeWidth={1.8}/>)}</LineChart></ResponsiveContainer></Panel><div className="two"><Panel code="02 / STORAGE" title={t.storage}><ResponsiveContainer width="100%" height={300}><LineChart data={storageCapacity}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={58}/><Tooltip contentStyle={tip} labelFormatter={(value) => month(value, lang)} formatter={(value: number, name: string) => { const meta = Object.values(STORAGE).find((item) => item.key === name); return [`${formatInteger(Number(value), lang)} MW`, meta?.[lang] ?? name]; }}/>{Object.values(STORAGE).map((item) => <Line key={item.key} dataKey={item.key} name={item.key} stroke={item.color} dot={false} strokeWidth={2.2}/>)}</LineChart></ResponsiveContainer></Panel><Panel code="03 / CO₂-EQ" title={t.carbon}><ResponsiveContainer width="100%" height={300}><LineChart data={carbon}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis domain={[0, 100]} {...axis} unit="%" width={58}/><Tooltip contentStyle={tip} labelFormatter={(value) => month(value, lang)} formatter={(value: number) => [`${new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 1 }).format(Number(value))}%`, t.carbon]}/><Line dataKey="share" stroke="#E56857" dot={false} strokeWidth={2.5}/></LineChart></ResponsiveContainer><p className="chart-note">{t.carbonNote}</p></Panel></div></>}

    {section === "marginal" && <div className="two"><Panel code="01 / HISTORY" title={t.archive}><div className="cutoff"><strong>18 MAR 2025</strong><span>{t.contextOnly}</span></div><Empty title={t.unavailable} copy={t.noRows}/></Panel><Panel code="02 / CONTEXT" title={t.context}><div className="flag">{t.contextOnly}</div>{data.omie_prices.length ? <ResponsiveContainer width="100%" height={300}><LineChart data={data.omie_prices}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => formatInteger(value, lang)} {...axis} width={58}/><Tooltip contentStyle={tip} labelFormatter={(value) => month(value, lang)} formatter={(value: number) => [`€${formatPrice(Number(value), lang)}/MWh`, lang === "es" ? "Precio España" : "Spain price"]}/><Line dataKey="price_es_eur_mwh" stroke="#9EF01A" dot={false} strokeWidth={2.5}/></LineChart></ResponsiveContainer> : <Empty title={t.unavailable} copy={t.noRows}/>}</Panel></div>}

    <footer><p className="kicker">{t.sources}</p>{data.sources.map((source) => <a href={source.url} key={source.key}>{source.key}<span>{source.last_update ? new Date(source.last_update).toLocaleDateString(locale(lang)) : "—"}</span></a>)}</footer>
  </main></div>;
}
