import { useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react";
import { motion } from "framer-motion";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { loadDashboard, loadHourlyYears } from "./api";
import type { DashboardData, HourlyShard, Language, Manifest, SectionKey, SeriesRow } from "./types";

type Tech = { key: string; en: string; es: string; color: string; family: "renewable" | "zero" | "fossil" };
type Preset = "all" | "renewable" | "low" | "fossil" | "custom";
type InterconnectorMode = "split" | "net";

const TECH: Record<string, Tech> = {
  "Hidráulica": { key: "hydro", en: "Hydro", es: "Hidráulica", color: "#2E7DD7", family: "renewable" },
  "Eólica": { key: "wind", en: "Wind", es: "Eólica", color: "#20B785", family: "renewable" },
  "Solar fotovoltaica": { key: "solar_pv", en: "Solar PV", es: "Solar fotovoltaica", color: "#F0C94A", family: "renewable" },
  "Solar térmica": { key: "solar_thermal", en: "Solar thermal", es: "Solar térmica", color: "#E58A35", family: "renewable" },
  "Otras renovables": { key: "other_renewables", en: "Other renewables", es: "Otras renovables", color: "#89C05A", family: "renewable" },
  "Residuos renovables": { key: "renewable_waste", en: "Renewable waste", es: "Residuos renovables", color: "#68A95B", family: "renewable" },
  "Hidroeólica": { key: "hydro_wind", en: "Hydro-wind", es: "Hidroeólica", color: "#47B8B0", family: "renewable" },
  Nuclear: { key: "nuclear", en: "Nuclear", es: "Nuclear", color: "#9F85D8", family: "zero" },
  "Ciclo combinado": { key: "combined_cycle", en: "Combined cycle", es: "Ciclo combinado", color: "#E56857", family: "fossil" },
  "Cogeneración": { key: "cogeneration", en: "Cogeneration", es: "Cogeneración", color: "#C98772", family: "fossil" },
  "Carbón": { key: "coal", en: "Coal", es: "Carbón", color: "#7C8991", family: "fossil" },
  "Fuel + Gas": { key: "fuel_gas", en: "Fuel + gas", es: "Fuel + gas", color: "#A67363", family: "fossil" },
  "Motores diésel": { key: "diesel", en: "Diesel engines", es: "Motores diésel", color: "#9A6152", family: "fossil" },
  "Turbina de gas": { key: "gas_turbine", en: "Gas turbine", es: "Turbina de gas", color: "#B57861", family: "fossil" },
  "Turbina de vapor": { key: "steam_turbine", en: "Steam turbine", es: "Turbina de vapor", color: "#8E655A", family: "fossil" },
  "Residuos no renovables": { key: "nonrenewable_waste", en: "Non-renewable waste", es: "Residuos no renovables", color: "#69777D", family: "fossil" },
};

const STORAGE: Record<string, { key: string; en: string; es: string; color: string }> = {
  "Turbinación bombeo": { key: "pumped_storage", en: "Pumped storage", es: "Turbinación de bombeo", color: "#2E7DD7" },
  "Batería": { key: "battery", en: "Battery", es: "Batería", color: "#9EF01A" },
};

const BORDER = {
  France: { en: "France", es: "Francia", color: "#2E7DD7" },
  Portugal: { en: "Portugal", es: "Portugal", color: "#20B785" },
  Morocco: { en: "Morocco", es: "Marruecos", color: "#E58A35" },
  Andorra: { en: "Andorra", es: "Andorra", color: "#9F85D8" },
} as const;

const C = {
  en: {
    strap: "an analysis of Spain's electricity system", generation: "Generation", interconnectors: "Interconnectors", coverage: "Coverage", system: "System", method: "Sources / method", headingLabel: "Spain / electricity",
    generationTitle: "How Spain generates electricity", generationCopy: "Generation by technology. National system.", mix: "Generation mix — month by month", rolling: "12-month source trend", balance: "Generation and demand", shape: "The shape of a day",
    interTitle: "Cross-border electricity flows", interCopy: "Electricity imported from and exported to the interconnected grids of France, Portugal, Morocco and Andorra.", bothFlows: "Imports + exports", netFlows: "Net by country", selectedBorders: "Selected countries", net: "net",
    coverageTitle: "When selected sources cover demand", coverageCopy: "Choose technologies, a demand threshold and a period to measure how often they supplied that share of demand (or higher).", coverageResult: "Hourly coverage analysis", threshold: "Demand threshold", selectedSources: "Selected technologies",
    systemTitle: "Capacity, storage and carbon context", systemCopy: "Track the generation fleet, emerging storage capacity and the carbon profile of electricity production.", installed: "Installed capacity — month by month", storage: "Storage capacity", carbon: "Generation associated with CO₂-eq emissions",
    carbonNote: "This is the monthly share of electricity generated by technologies that REE classifies as having associated CO₂-equivalent emissions. It is a share of generation, not an emissions-intensity measure in gCO₂/kWh.",
    methodTitle: "Sources and method", methodCopy: "Where the data comes from, what each series represents and how missing or incomplete observations are handled.", dataSources: "Data sources", methodology: "Method", lastUpdate: "Last update", visitPortfolio: "danielalmazan.com", week: "Week", weekdays: "Weekdays", dates: "Dates", resetFilters: "Reset filters", allWeeks: "All weeks", allWeekdays: "All weekdays", allDates: "All dates", selectedCount: "selected", addDate: "Add date", removeDate: "Remove", noDates: "No dates match the preceding filters", shapeFilters: "Chart-specific filters", observations: "hourly observations",
    methodMissing: "Missing hourly observations are excluded from calculations and reported; values are never interpolated. UTC storage preserves both hours on the autumn daylight-saving transition, while charts use Europe/Madrid local time.", methodGeography: "Monthly REData series describe Spain's national system. Hourly e·sios generation and demand describe the peninsular system. These geographies are labelled and are not silently combined.",
    all: "All", renewables: "Renewables", lowCarbon: "Low carbon", fossil: "Fossil", from: "From", to: "To", sources: "Sources", geography: "Geography", national: "Spain · national system", imports: "imports", exports: "exports", unavailable: "Not available",
    hourlyNeeded: "Hourly technology data needs e·sios access", hourlyDetail: "The public REData generation and demand widgets return errors at hourly granularity. No monthly proxy is used for an hourly calculation.", hourlyLoading: "Loading measured hourly data", hourlyLoadingDetail: "The selected yearly shards are being loaded from the published e·sios dataset.", hourlyShapeNote: "Average share of demand supplied by each selected technology at every Madrid-local hour in the selected period.", coverageShare: "Hours meeting threshold", hoursMet: "Hours met", hoursEvaluated: "Hours evaluated", excludedHours: "Hours excluded", byMonth: "Coverage by month", byHour: "Coverage by hour of day", hour: "Hour", coverageNote: "An hour counts when the selected e·sios generation series together equal or exceed the chosen share of measured demand. Missing demand or source observations are excluded; values are never interpolated.", groupedCogeneration: "In e·sios real-time data, cogeneration is published together with other generation.", noRows: "No validated observations are available for this module yet.", error: "Public data could not be loaded.", retry: "Retry",
  },
  es: {
    strap: "un análisis del sistema eléctrico español", generation: "Generación", interconnectors: "Interconexiones", coverage: "Cobertura", system: "Sistema", method: "Fuentes / método", headingLabel: "España / electricidad",
    generationTitle: "Cómo genera electricidad España", generationCopy: "Generación por tecnología. Sistema nacional.", mix: "Mix de generación — mes a mes", rolling: "Tendencia de fuentes a 12 meses", balance: "Generación y demanda", shape: "La forma de un día",
    interTitle: "Flujos eléctricos transfronterizos", interCopy: "Electricidad importada y exportada a las redes interconectadas de Francia, Portugal, Marruecos y Andorra.", bothFlows: "Importaciones + exportaciones", netFlows: "Neto por país", selectedBorders: "Países elegidos", net: "neto",
    coverageTitle: "Cuándo cubren la demanda las fuentes elegidas", coverageCopy: "Elige tecnologías, un umbral de demanda y un periodo para medir con qué frecuencia aportaron esa proporción de la demanda (o más).", coverageResult: "Análisis horario de cobertura", threshold: "Umbral de demanda", selectedSources: "Tecnologías elegidas",
    systemTitle: "Contexto de capacidad, almacenamiento y carbono", systemCopy: "Sigue la evolución del parque generador, la nueva capacidad de almacenamiento y el perfil de carbono de la producción eléctrica.", installed: "Potencia instalada — mes a mes", storage: "Capacidad de almacenamiento", carbon: "Generación asociada a emisiones de CO₂-eq",
    carbonNote: "Es la proporción mensual de electricidad producida por tecnologías que REE clasifica como asociadas a emisiones de CO₂ equivalente. Es una cuota de generación, no una medida de intensidad en gCO₂/kWh.",
    methodTitle: "Fuentes y método", methodCopy: "De dónde proceden los datos, qué representa cada serie y cómo se tratan las observaciones ausentes o incompletas.", dataSources: "Fuentes de datos", methodology: "Método", lastUpdate: "Última actualización", visitPortfolio: "danielalmazan.com", week: "Semana", weekdays: "Días", dates: "Fechas", resetFilters: "Restablecer filtros", allWeeks: "Todas las semanas", allWeekdays: "Todos los días", allDates: "Todas las fechas", selectedCount: "seleccionados", addDate: "Añadir fecha", removeDate: "Quitar", noDates: "Ninguna fecha coincide con los filtros anteriores", shapeFilters: "Filtros propios del gráfico", observations: "observaciones horarias",
    methodMissing: "Las observaciones horarias ausentes se excluyen de los cálculos y se contabilizan; nunca se interpolan. El almacenamiento en UTC conserva las dos horas del cambio de otoño, mientras los gráficos usan la hora local Europe/Madrid.", methodGeography: "Las series mensuales de REData describen el sistema nacional español. La generación y demanda horarias de e·sios describen el sistema peninsular. Estos ámbitos se etiquetan y no se combinan de forma silenciosa.",
    all: "Todas", renewables: "Renovables", lowCarbon: "Bajas en carbono", fossil: "Fósiles", from: "Desde", to: "Hasta", sources: "Fuentes", geography: "Ámbito", national: "España · sistema nacional", imports: "importaciones", exports: "exportaciones", unavailable: "No disponible",
    hourlyNeeded: "Los datos horarios por tecnología necesitan acceso a e·sios", hourlyDetail: "Los indicadores públicos de generación y demanda de REData devuelven errores a escala horaria. No se utiliza una aproximación mensual para un cálculo horario.", hourlyLoading: "Cargando datos horarios medidos", hourlyLoadingDetail: "Se están cargando los archivos anuales seleccionados del conjunto publicado de e·sios.", hourlyShapeNote: "Proporción media de la demanda cubierta por cada tecnología seleccionada en cada hora local de Madrid durante el periodo elegido.", coverageShare: "Horas que alcanzan el umbral", hoursMet: "Horas cumplidas", hoursEvaluated: "Horas evaluadas", excludedHours: "Horas excluidas", byMonth: "Cobertura por mes", byHour: "Cobertura por hora del día", hour: "Hora", coverageNote: "Una hora cuenta cuando las series de generación e·sios elegidas igualan o superan juntas la proporción seleccionada de demanda medida. Se excluyen las observaciones ausentes de demanda o fuente; nunca se interpolan valores.", groupedCogeneration: "En los datos en tiempo real de e·sios, la cogeneración se publica junto con otra generación.", noRows: "Todavía no hay observaciones validadas para este módulo.", error: "No se pudieron cargar los datos públicos.", retry: "Reintentar",
  },
} as const;

const allTech = Object.values(TECH);
const techByKey = new Map(allTech.map((tech) => [tech.key, tech]));
const getLang = (): Language => new URLSearchParams(location.search).get("lang") === "es" ? "es" : "en";
const locale = (lang: Language) => lang === "es" ? "es-ES" : "en-GB";
const formatInteger = (value: number, lang: Language) => {
  const rounded = Math.round(value); const formatted = new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 0, useGrouping: true }).format(rounded);
  if (Math.abs(rounded) >= 1000 && Math.abs(rounded) < 10000 && !/[.,\s]/.test(formatted)) { const digits = String(Math.abs(rounded)); return `${rounded < 0 ? "-" : ""}${digits.slice(0, -3)}${lang === "es" ? "." : ","}${digits.slice(-3)}`; }
  return formatted;
};
const compact = (value: number, lang: Language) => new Intl.NumberFormat(locale(lang), { notation: "compact", maximumFractionDigits: 1 }).format(value);
const month = (value: string, lang: Language) => new Intl.DateTimeFormat(locale(lang), { month: "short", year: "2-digit", timeZone: "UTC" }).format(new Date(`${value}-01T00:00:00Z`));

function reshape(rows: SeriesRow[], dictionary: Record<string, { key: string }>) {
  const result = new Map<string, Record<string, string | number>>();
  rows.forEach((row) => {
    const meta = dictionary[row.series];
    if (!meta) return;
    const item = result.get(row.period) ?? { period: row.period, total: 0 };
    item[meta.key] = row.value; item.total = Number(item.total) + row.value; result.set(row.period, item);
  });
  return [...result.values()].sort((a, b) => String(a.period).localeCompare(String(b.period)));
}

function rolling(rows: Array<Record<string, string | number>>, keys: string[]) {
  return rows.map((row, index) => {
    const window = rows.slice(Math.max(0, index - 11), index + 1);
    const out: Record<string, string | number> = { period: row.period };
    keys.forEach((key) => { out[key] = window.reduce((sum, item) => sum + Number(item[key] ?? 0), 0) / window.length; });
    return out;
  });
}

function Panel({ code, title, children }: { code: string; title: string; children: ReactNode }) {
  return <motion.section className="panel" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><header><span>{code}</span><h2>{title}</h2></header>{children}</motion.section>;
}
function Empty({ title, copy }: { title: string; copy: string }) { return <div className="empty"><b>!</b><div><strong>{title}</strong><p>{copy}</p></div></div>; }
function TechnologyToggles({ active, lang, toggle, label, available }: { active: Set<string>; lang: Language; toggle: (key: string) => void; label: string; available?: Set<string> }) {
  return <div className="technology-filter"><span>{label}</span><div>{allTech.map((tech) => { const disabled = available ? !available.has(tech.key) : false; return <button key={tech.key} className={active.has(tech.key) ? "active" : ""} aria-pressed={active.has(tech.key)} disabled={disabled} onClick={() => toggle(tech.key)}><i style={{ "--series": tech.color } as CSSProperties}/>{tech[lang]}</button>; })}</div></div>;
}

const madridClock = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Madrid", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", hourCycle: "h23" });
function localTime(timestamp: string) {
  const parts = Object.fromEntries(madridClock.formatToParts(new Date(timestamp)).map((part) => [part.type, part.value]));
  const date = `${parts.year}-${parts.month}-${parts.day}`;
  const weekday = new Date(`${date}T12:00:00Z`).getUTCDay();
  const monday = new Date(`${date}T12:00:00Z`); monday.setUTCDate(monday.getUTCDate() - ((weekday + 6) % 7));
  return { month: `${parts.year}-${parts.month}`, date, weekday, week: monday.toISOString().slice(0, 10), hour: Number(parts.hour) % 24 };
}
function yearsInRange(from: string, to: string, available: number[]) {
  const first = Number(from.slice(0, 4)); const last = Number(to.slice(0, 4));
  return available.filter((year) => year >= first && year <= last);
}

const WEEKDAYS = [1, 2, 3, 4, 5, 6, 0];
function weekdayName(day: number, lang: Language) {
  const sunday = new Date(Date.UTC(2024, 0, 7 + day));
  return new Intl.DateTimeFormat(locale(lang), { weekday: "short", timeZone: "UTC" }).format(sunday);
}
function dateLabel(value: string, lang: Language) {
  return new Intl.DateTimeFormat(locale(lang), { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`));
}

function WeekdayFilter({ selected, setSelected, lang, label, allLabel, selectedLabel }: { selected: Set<number>; setSelected: (value: Set<number>) => void; lang: Language; label: string; allLabel: string; selectedLabel: string }) {
  const toggle = (day: number) => { const next = new Set(selected); next.has(day) ? next.delete(day) : next.add(day); setSelected(next); };
  return <details className="filter-menu"><summary><span>{label}</span><strong>{selected.size ? `${selected.size} ${selectedLabel}` : allLabel}</strong></summary><div>{WEEKDAYS.map((day) => <label key={day}><input type="checkbox" checked={selected.has(day)} onChange={() => toggle(day)}/><span>{weekdayName(day, lang)}</span></label>)}</div></details>;
}

export default function App() {
  const [lang, setLang] = useState<Language>(getLang); const [section, setSection] = useState<SectionKey>("generation");
  const [data, setData] = useState<DashboardData | null>(null); const [manifest, setManifest] = useState<Manifest | null>(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0);
  const [preset, setPreset] = useState<Preset>("all"); const [enabled, setEnabled] = useState(() => new Set(allTech.map((tech) => tech.key)));
  const [from, setFrom] = useState("2019-01"); const [to, setTo] = useState("2026-12");
  const [systemFrom, setSystemFrom] = useState("2019-01"); const [systemTo, setSystemTo] = useState("2026-12");
  const [interFrom, setInterFrom] = useState("2019-01"); const [interTo, setInterTo] = useState("2026-12");
  const [interMode, setInterMode] = useState<InterconnectorMode>("split"); const [enabledBorders, setEnabledBorders] = useState(() => new Set<keyof typeof BORDER>(Object.keys(BORDER) as Array<keyof typeof BORDER>));
  const [coverageFrom, setCoverageFrom] = useState("2025-01"); const [coverageTo, setCoverageTo] = useState("2026-12"); const [coverageThreshold, setCoverageThreshold] = useState(50);
  const [coverageTech, setCoverageTech] = useState(() => new Set(["solar_pv"]));
  const [hourlyShards, setHourlyShards] = useState<HourlyShard[]>([]); const [hourlyLoading, setHourlyLoading] = useState(false); const [hourlyError, setHourlyError] = useState("");
  const [shapeFrom, setShapeFrom] = useState("2019-01"); const [shapeTo, setShapeTo] = useState("2026-08"); const [shapeWeek, setShapeWeek] = useState("");
  const [shapeWeekdays, setShapeWeekdays] = useState(() => new Set<number>()); const [shapeDates, setShapeDates] = useState(() => new Set<string>()); const [pendingShapeDate, setPendingShapeDate] = useState("");
  const t = C[lang];

  useEffect(() => { document.documentElement.lang = lang; }, [lang]);
  useEffect(() => {
    const closeOpenMenus = (event: PointerEvent) => {
      const target = event.target instanceof Node ? event.target : null;
      document.querySelectorAll<HTMLDetailsElement>(".filter-menu[open]").forEach((menu) => {
        if (!target || !menu.contains(target)) menu.open = false;
      });
    };
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") document.querySelectorAll<HTMLDetailsElement>(".filter-menu[open]").forEach((menu) => { menu.open = false; });
    };
    document.addEventListener("pointerdown", closeOpenMenus);
    document.addEventListener("keydown", closeOnEscape);
    return () => { document.removeEventListener("pointerdown", closeOpenMenus); document.removeEventListener("keydown", closeOnEscape); };
  }, []);
  useEffect(() => { loadDashboard().then(({ dashboard, manifest: loaded }) => { const start = loaded.coverage.monthly_start ?? "2019-01"; const end = loaded.coverage.monthly_end ?? "2026-12"; setData(dashboard); setManifest(loaded); setFrom(start); setTo(end); setShapeFrom(start); setShapeTo(end); setSystemFrom(start); setSystemTo(end); setInterFrom(start); setInterTo(end); setCoverageTo(end); }).catch((reason) => setError(String(reason))); }, [attempt]);
  useEffect(() => {
    if (data?.hourly.status !== "available" || (section !== "coverage" && section !== "generation")) return;
    const range = section === "coverage" ? [coverageFrom, coverageTo] : [shapeFrom, shapeTo];
    const years = yearsInRange(range[0], range[1], data.hourly.years);
    let cancelled = false; setHourlyLoading(true); setHourlyError("");
    loadHourlyYears(years).then((shards) => { if (!cancelled) setHourlyShards(shards); }).catch((reason) => { if (!cancelled) setHourlyError(String(reason)); }).finally(() => { if (!cancelled) setHourlyLoading(false); });
    return () => { cancelled = true; };
  }, [data, section, shapeFrom, shapeTo, coverageFrom, coverageTo]);
  const setLanguage = (next: Language) => { setLang(next); const url = new URL(location.href); next === "es" ? url.searchParams.set("lang", "es") : url.searchParams.delete("lang"); history.replaceState({}, "", url); document.documentElement.lang = next; };
  const applyPreset = (next: Exclude<Preset, "custom">) => { setPreset(next); setEnabled(new Set(allTech.filter((tech) => next === "all" || (next === "low" ? tech.family !== "fossil" : tech.family === next)).map((tech) => tech.key))); };
  const toggleTechnology = (key: string) => { setPreset("custom"); setEnabled((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; }); };
  const toggleCoverage = (key: string) => setCoverageTech((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; });
  const toggleBorder = (key: keyof typeof BORDER) => setEnabledBorders((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; });

  const activeTech = allTech.filter((tech) => enabled.has(tech.key)); const activeKeys = activeTech.map((tech) => tech.key);
  const allGeneration = useMemo(() => data ? reshape(data.generation, TECH) : [], [data]);
  const generation = useMemo(() => allGeneration.filter((row) => String(row.period) >= from && String(row.period) <= to), [allGeneration, from, to]);
  const trend = useMemo(() => rolling(allGeneration, activeKeys).filter((row) => String(row.period) >= from && String(row.period) <= to), [allGeneration, activeKeys.join("|"), from, to]);
  const demandMap = new Map((data?.demand ?? []).filter((row) => row.series === "Demanda").map((row) => [row.period, row.value]));
  const balance = generation.map((row) => ({ period: row.period, generation: row.total, demand: demandMap.get(String(row.period)) }));
  const capacity = useMemo(() => data ? reshape(data.capacity, TECH).filter((row) => String(row.period) >= systemFrom && String(row.period) <= systemTo) : [], [data, systemFrom, systemTo]);
  const storageCapacity = useMemo(() => data ? reshape(data.storage_capacity ?? [], STORAGE).filter((row) => String(row.period) >= systemFrom && String(row.period) <= systemTo) : [], [data, systemFrom, systemTo]);
  const carbon = (data?.emissions_context ?? []).filter((row) => row.series === "Con emisiones de CO2 eq." && row.period >= systemFrom && row.period <= systemTo);
  const exchangeData = useMemo(() => { const byPeriod = new Map<string, Record<string, string | number>>(); (data?.exchanges ?? []).filter((row) => row.period >= interFrom && row.period <= interTo).forEach((row) => { const item = byPeriod.get(row.period) ?? { period: row.period }; item[`${row.country}_${row.direction}`] = row.value_gwh; byPeriod.set(row.period, item); }); return [...byPeriod.values()].map((item) => { Object.keys(BORDER).forEach((country) => { item[`${country}_net`] = Number(item[`${country}_import`] ?? 0) + Number(item[`${country}_export`] ?? 0); }); return item; }).sort((a, b) => String(a.period).localeCompare(String(b.period))); }, [data, interFrom, interTo]);
  const activeBorders = (Object.entries(BORDER) as Array<[keyof typeof BORDER, (typeof BORDER)[keyof typeof BORDER]]>).filter(([country]) => enabledBorders.has(country));
  const hourlyKeys = new Set((data?.hourly.columns ?? []).slice(2));
  const coverage = useMemo(() => {
    const selected = [...coverageTech].filter((key) => hourlyKeys.has(key));
    const monthly = new Map<string, { met: number; total: number }>(); const hours = Array.from({ length: 24 }, () => ({ met: 0, total: 0 }));
    let met = 0; let evaluated = 0; let excluded = 0;
    hourlyShards.forEach((shard) => { const index = new Map(shard.columns.map((key, position) => [key, position])); shard.rows.forEach((row) => {
      const clock = localTime(String(row[0])); if (clock.month < coverageFrom || clock.month > coverageTo) return;
      const demandIndex = index.get("demand"); const sourceIndexes = selected.map((key) => index.get(key));
      const demand = demandIndex === undefined ? null : row[demandIndex]; const values = sourceIndexes.map((position) => position === undefined ? null : row[position]);
      if (!selected.length || typeof demand !== "number" || demand <= 0 || values.some((value) => typeof value !== "number")) { excluded += 1; return; }
      const covered = values.reduce<number>((sum, value) => sum + Number(value), 0) / demand * 100 >= coverageThreshold;
      const monthBin = monthly.get(clock.month) ?? { met: 0, total: 0 }; monthBin.total += 1; if (covered) monthBin.met += 1; monthly.set(clock.month, monthBin);
      hours[clock.hour].total += 1; if (covered) hours[clock.hour].met += 1; evaluated += 1; if (covered) met += 1;
    }); });
    return { met, evaluated, excluded, share: evaluated ? met / evaluated * 100 : 0, monthly: [...monthly].sort(([a], [b]) => a.localeCompare(b)).map(([period, value]) => ({ period, share: value.met / value.total * 100, met: value.met, total: value.total })), hours: hours.map((value, hour) => ({ hour, label: `${String(hour).padStart(2, "0")}:00`, share: value.total ? value.met / value.total * 100 : null, met: value.met, total: value.total })) };
  }, [hourlyShards, coverageFrom, coverageTo, coverageThreshold, [...coverageTech].sort().join("|"), [...hourlyKeys].join("|")]);
  const shapeCalendar = useMemo(() => {
    const dates = new Map<string, { weekday: number; week: string }>();
    hourlyShards.forEach((shard) => shard.rows.forEach((row) => { const clock = localTime(String(row[0])); if (clock.month >= shapeFrom && clock.month <= shapeTo) dates.set(clock.date, { weekday: clock.weekday, week: clock.week }); }));
    const weeks = [...new Set([...dates.values()].map((item) => item.week))].sort();
    const availableDates = [...dates].filter(([, item]) => (!shapeWeek || item.week === shapeWeek) && (!shapeWeekdays.size || shapeWeekdays.has(item.weekday))).map(([value]) => value).sort();
    return { weeks, availableDates, dateSet: new Set(availableDates) };
  }, [hourlyShards, shapeFrom, shapeTo, shapeWeek, [...shapeWeekdays].sort().join("|")]);
  useEffect(() => {
    if (shapeWeek && !shapeCalendar.weeks.includes(shapeWeek)) setShapeWeek("");
    setShapeDates((current) => { const next = new Set([...current].filter((value) => shapeCalendar.dateSet.has(value))); return next.size === current.size ? current : next; });
  }, [shapeCalendar]);
  const hourlyShapeResult = useMemo(() => {
    const selected = activeTech.filter((tech) => hourlyKeys.has(tech.key)); const bins = Array.from({ length: 24 }, () => ({ observations: 0, sums: new Map<string, number>(), counts: new Map<string, number>() }));
    let observations = 0;
    hourlyShards.forEach((shard) => { const index = new Map(shard.columns.map((key, position) => [key, position])); shard.rows.forEach((row) => {
      const clock = localTime(String(row[0]));
      if (clock.month < shapeFrom || clock.month > shapeTo || (shapeWeek && clock.week !== shapeWeek) || (shapeWeekdays.size && !shapeWeekdays.has(clock.weekday)) || (shapeDates.size && !shapeDates.has(clock.date))) return;
      const demandPosition = index.get("demand"); const demand = demandPosition === undefined ? null : row[demandPosition]; if (typeof demand !== "number" || demand <= 0) return;
      bins[clock.hour].observations += 1; observations += 1;
      selected.forEach((tech) => { const position = index.get(tech.key); const value = position === undefined ? null : row[position]; if (typeof value !== "number") return; bins[clock.hour].sums.set(tech.key, (bins[clock.hour].sums.get(tech.key) ?? 0) + value / demand * 100); bins[clock.hour].counts.set(tech.key, (bins[clock.hour].counts.get(tech.key) ?? 0) + 1); });
    }); });
    return { observations, rows: bins.map((bin, hour) => ({ hour: `${String(hour).padStart(2, "0")}:00`, ...Object.fromEntries(selected.map((tech) => [tech.key, bin.counts.get(tech.key) ? (bin.sums.get(tech.key) ?? 0) / bin.counts.get(tech.key)! : null])) })) };
  }, [hourlyShards, shapeFrom, shapeTo, shapeWeek, [...shapeWeekdays].sort().join("|"), [...shapeDates].sort().join("|"), activeKeys.join("|"), [...hourlyKeys].join("|")]);
  const hourlyShape = hourlyShapeResult.rows;
  const activeHourlyTech = activeTech.filter((tech) => hourlyKeys.has(tech.key));
  const resetShapeFilters = () => { const start = manifest?.coverage.monthly_start ?? "2019-01"; const end = manifest?.coverage.monthly_end ?? "2026-08"; setShapeFrom(start); setShapeTo(end); setShapeWeek(""); setShapeWeekdays(new Set()); setShapeDates(new Set()); setPendingShapeDate(""); };
  const addShapeDate = () => { if (pendingShapeDate && shapeCalendar.dateSet.has(pendingShapeDate)) { setShapeDates((current) => new Set(current).add(pendingShapeDate)); setPendingShapeDate(""); } };

  const title: Record<SectionKey, [string, string]> = { generation: [t.generationTitle, t.generationCopy], interconnectors: [t.interTitle, t.interCopy], coverage: [t.coverageTitle, t.coverageCopy], system: [t.systemTitle, t.systemCopy], method: [t.methodTitle, t.methodCopy] };
  const nav: Array<[SectionKey, string]> = [["generation", t.generation], ["interconnectors", t.interconnectors], ["coverage", t.coverage], ["system", t.system], ["method", t.method]];
  const axis = { stroke: "#5D7481", fontSize: 11 }; const tip = { background: "#0C1824", border: "1px solid #29414E", borderRadius: 2, color: "#E8EEF0" };
  const technologyTooltip = (unit: "GWh" | "MW") => (value: number, name: string) => [`${formatInteger(Number(value), lang)} ${unit}`, techByKey.get(name)?.[lang] ?? name];

  if (error) return <main className="fatal"><p className="kicker">DATA / ERROR</p><h1>{t.error}</h1><code>{error}</code><button onClick={() => { setError(""); setAttempt((value) => value + 1); }}>{t.retry}</button></main>;
  if (!data || !manifest) return <main className="loading"><span/><p>LOADING PUBLIC DATA</p></main>;

  return <div className="shell">
    <header className="topbar">
      <a className="identity" href={import.meta.env.BASE_URL}><strong>E-Spain:</strong><span>{t.strap}</span></a>
      <nav>{nav.map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}>{label}</button>)}</nav>
      <div className="language"><button className={lang === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button><button className={lang === "es" ? "active" : ""} onClick={() => setLanguage("es")}>ES</button></div>
    </header>
    <main>
      <section className="section-head"><div><p className="kicker">{t.headingLabel}</p><h1>{section === "generation" && lang === "es" ? <>Cómo genera<br className="mobile-break"/> electricidad<br className="mobile-break"/> España</> : title[section][0]}</h1><p>{title[section][1]}</p></div><dl><div><dt>{t.geography}</dt><dd>{t.national}</dd></div></dl></section>

      {section === "generation" && <>
        <div className="controls"><div className="segments">{(["all", "renewable", "low", "fossil"] as const).map((value) => <button key={value} className={preset === value ? "active" : ""} onClick={() => applyPreset(value)}>{value === "all" ? t.all : value === "renewable" ? t.renewables : value === "low" ? t.lowCarbon : t.fossil}</button>)}</div><label>{t.from}<input type="month" value={from} max={to} onChange={(event) => setFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={to} min={from} onChange={(event) => setTo(event.target.value)}/></label></div>
        <TechnologyToggles active={enabled} lang={lang} toggle={toggleTechnology} label={t.selectedSources}/>
        <Panel code="01 / MIX" title={t.mix}><ResponsiveContainer width="100%" height={410}><AreaChart data={generation}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={68}/><Tooltip contentStyle={tip} formatter={technologyTooltip("GWh")} labelFormatter={(value) => month(value, lang)}/>{activeTech.map((tech) => <Area key={tech.key} dataKey={tech.key} name={tech.key} stackId="mix" stroke={tech.color} fill={tech.color} fillOpacity={0.88}/>)}</AreaChart></ResponsiveContainer></Panel>
        <div className="two"><Panel code="02 / TREND" title={t.rolling}><ResponsiveContainer width="100%" height={300}><LineChart data={trend}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={58}/><Tooltip contentStyle={tip} formatter={technologyTooltip("GWh")} labelFormatter={(value) => month(value, lang)}/>{activeTech.map((tech) => <Line key={tech.key} dataKey={tech.key} name={tech.key} stroke={tech.color} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></Panel><Panel code="03 / BALANCE" title={t.balance}><ResponsiveContainer width="100%" height={300}><LineChart data={balance}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={58}/><Tooltip contentStyle={tip} formatter={(value: number, name: string) => [`${formatInteger(Number(value), lang)} GWh`, name === "generation" ? t.generation : name === "demand" ? (lang === "es" ? "Demanda" : "Demand") : name]} labelFormatter={(value) => month(value, lang)}/><Line dataKey="generation" stroke="#9EF01A" dot={false} strokeWidth={2}/><Line dataKey="demand" stroke="#E8EEF0" dot={false}/></LineChart></ResponsiveContainer></Panel></div>
        <Panel code="04 / HOURLY" title={t.shape}>
          <div className="shape-filter-wrap"><div className="shape-filter-label">{t.shapeFilters}</div><div className="shape-filters">
            <label><span>{t.from}</span><input type="month" value={shapeFrom} max={shapeTo} onInput={(event) => setShapeFrom(event.currentTarget.value)} onChange={(event) => setShapeFrom(event.target.value)}/></label>
            <label><span>{t.to}</span><input type="month" value={shapeTo} min={shapeFrom} onInput={(event) => setShapeTo(event.currentTarget.value)} onChange={(event) => setShapeTo(event.target.value)}/></label>
            <label><span>{t.week}</span><select value={shapeWeek} onChange={(event) => setShapeWeek(event.target.value)}><option value="">{t.allWeeks}</option>{shapeCalendar.weeks.map((week) => <option key={week} value={week}>{dateLabel(week, lang)}</option>)}</select></label>
            <WeekdayFilter selected={shapeWeekdays} setSelected={setShapeWeekdays} lang={lang} label={t.weekdays} allLabel={t.allWeekdays} selectedLabel={t.selectedCount}/>
            <div className="date-filter"><span>{t.dates}</span><div><input type="date" list="shape-dates" value={pendingShapeDate} min={shapeCalendar.availableDates[0]} max={shapeCalendar.availableDates[shapeCalendar.availableDates.length - 1]} onInput={(event) => setPendingShapeDate(event.currentTarget.value)} onChange={(event) => setPendingShapeDate(event.target.value)}/><datalist id="shape-dates">{shapeCalendar.availableDates.map((value) => <option key={value} value={value}/>)}</datalist><button disabled={!shapeCalendar.dateSet.has(pendingShapeDate)} onClick={addShapeDate}>{t.addDate}</button></div>{shapeDates.size ? <div className="date-chips">{[...shapeDates].sort().map((value) => <button key={value} onClick={() => setShapeDates((current) => { const next = new Set(current); next.delete(value); return next; })}>{dateLabel(value, lang)} ×</button>)}</div> : <small>{t.allDates}</small>}</div>
            <button className="reset-filters" onClick={resetShapeFilters}>{t.resetFilters}</button>
          </div></div>
          {data.hourly.status !== "available" ? <Empty title={t.hourlyNeeded} copy={t.hourlyDetail}/> : hourlyLoading ? <Empty title={t.hourlyLoading} copy={t.hourlyLoadingDetail}/> : hourlyError ? <Empty title={t.error} copy={hourlyError}/> : activeHourlyTech.length && hourlyShapeResult.observations ? <><ResponsiveContainer width="100%" height={340}><LineChart data={hourlyShape}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="hour" {...axis}/><YAxis unit="%" {...axis} width={56}/><Tooltip contentStyle={tip} formatter={(value: number, name: string) => [`${new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 1 }).format(Number(value))}%`, techByKey.get(name)?.[lang] ?? name]}/>{activeHourlyTech.map((tech) => <Line key={tech.key} dataKey={tech.key} name={tech.key} stroke={tech.color} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer><p className="chart-note">{t.hourlyShapeNote} {formatInteger(hourlyShapeResult.observations, lang)} {t.observations}.</p></> : <Empty title={t.unavailable} copy={t.noRows}/>}
        </Panel>
      </>}

      {section === "interconnectors" && <><div className="controls"><div className="segments"><button className={interMode === "split" ? "active" : ""} onClick={() => setInterMode("split")}>{t.bothFlows}</button><button className={interMode === "net" ? "active" : ""} onClick={() => setInterMode("net")}>{t.netFlows}</button></div><label>{t.from}<input type="month" value={interFrom} max={interTo} onChange={(event) => setInterFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={interTo} min={interFrom} onChange={(event) => setInterTo(event.target.value)}/></label></div><div className="technology-filter country-filter"><span>{t.selectedBorders}</span><div>{(Object.entries(BORDER) as Array<[keyof typeof BORDER, (typeof BORDER)[keyof typeof BORDER]]>).map(([country, meta]) => <button key={country} className={enabledBorders.has(country) ? "active" : ""} aria-pressed={enabledBorders.has(country)} onClick={() => toggleBorder(country)}><i style={{ "--series": meta.color } as CSSProperties}/>{meta[lang]}</button>)}</div></div><Panel code="01 / BORDERS" title={t.interTitle}>{exchangeData.length ? <ResponsiveContainer width="100%" height={430}><BarChart data={exchangeData} stackOffset="sign"><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={70}/><ReferenceLine y={0} stroke="#E8EEF0"/><Tooltip cursor={{ fill: "transparent" }} contentStyle={tip} labelStyle={{ color: "#E8EEF0" }} labelFormatter={(value) => month(value, lang)} formatter={(value: number, name: string) => { const [country, direction] = name.split("_"); const meta = BORDER[country as keyof typeof BORDER]; const amount = direction === "net" ? Number(value) : Math.abs(Number(value)); return [`${formatInteger(amount, lang)} GWh`, `${meta?.[lang] ?? country} · ${direction === "import" ? t.imports : direction === "export" ? t.exports : t.net}`]; }}/>{interMode === "split" ? activeBorders.flatMap(([country, meta]) => [<Bar key={`${country}_import`} dataKey={`${country}_import`} stackId="imports" fill={meta.color}/>, <Bar key={`${country}_export`} dataKey={`${country}_export`} stackId="exports" fill={meta.color} fillOpacity={0.62}/>]) : activeBorders.map(([country, meta]) => <Bar key={`${country}_net`} dataKey={`${country}_net`} stackId="net" fill={meta.color}/>)}</BarChart></ResponsiveContainer> : <Empty title={t.unavailable} copy={t.noRows}/>}</Panel></>}

      {section === "coverage" && <><div className="coverage-controls"><TechnologyToggles active={coverageTech} lang={lang} toggle={toggleCoverage} label={t.selectedSources} available={hourlyKeys}/><div className="coverage-parameters"><label>{t.threshold}<span><input type="range" min="1" max="100" value={coverageThreshold} onChange={(event) => setCoverageThreshold(Number(event.target.value))}/><output>{coverageThreshold}%</output></span></label><label>{t.from}<input type="month" value={coverageFrom} max={coverageTo} onChange={(event) => setCoverageFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={coverageTo} min={coverageFrom} onChange={(event) => setCoverageTo(event.target.value)}/></label></div></div><Panel code="01 / THRESHOLD" title={t.coverageResult}>{data.hourly.status !== "available" ? <Empty title={t.hourlyNeeded} copy={t.hourlyDetail}/> : hourlyLoading ? <Empty title={t.hourlyLoading} copy={t.hourlyLoadingDetail}/> : hourlyError ? <Empty title={t.error} copy={hourlyError}/> : coverage.evaluated ? <><div className="coverage-summary"><div className="coverage-primary"><span>{t.coverageShare}</span><strong>{new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 1 }).format(coverage.share)}%</strong></div><dl><div><dt>{t.hoursMet}</dt><dd>{formatInteger(coverage.met, lang)}</dd></div><div><dt>{t.hoursEvaluated}</dt><dd>{formatInteger(coverage.evaluated, lang)}</dd></div><div><dt>{t.excludedHours}</dt><dd>{formatInteger(coverage.excluded, lang)}</dd></div></dl></div><div className="two coverage-charts"><div><h3>{t.byMonth}</h3><ResponsiveContainer width="100%" height={280}><BarChart data={coverage.monthly}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis domain={[0, 100]} unit="%" {...axis} width={58}/><Tooltip cursor={{ fill: "transparent" }} contentStyle={tip} labelFormatter={(value) => month(value, lang)} formatter={(value: number) => [`${new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 1 }).format(Number(value))}%`, t.coverageShare]}/><Bar dataKey="share" fill="#9EF01A"/></BarChart></ResponsiveContainer></div><div><h3>{t.byHour}</h3><ResponsiveContainer width="100%" height={280}><BarChart data={coverage.hours}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="label" interval={2} {...axis}/><YAxis domain={[0, 100]} unit="%" {...axis} width={58}/><Tooltip cursor={{ fill: "transparent" }} contentStyle={tip} formatter={(value: number) => [`${new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 1 }).format(Number(value))}%`, t.coverageShare]}/><Bar dataKey="share" fill="#2E7DD7"/></BarChart></ResponsiveContainer></div></div><p className="chart-note">{t.coverageNote} {coverageTech.has("cogeneration") ? t.groupedCogeneration : ""}</p></> : <Empty title={t.unavailable} copy={t.noRows}/>}</Panel></>}

      {section === "system" && <><div className="controls"><label>{t.from}<input type="month" value={systemFrom} max={systemTo} onChange={(event) => setSystemFrom(event.target.value)}/></label><label>{t.to}<input type="month" value={systemTo} min={systemFrom} onChange={(event) => setSystemTo(event.target.value)}/></label></div><Panel code="01 / MW" title={t.installed}><ResponsiveContainer width="100%" height={420}><LineChart data={capacity}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={68}/><Tooltip contentStyle={tip} formatter={technologyTooltip("MW")} labelFormatter={(value) => month(value, lang)}/>{allTech.map((tech) => <Line key={tech.key} dataKey={tech.key} name={tech.key} stroke={tech.color} dot={false} strokeWidth={1.8}/>)}</LineChart></ResponsiveContainer></Panel><div className="two"><Panel code="02 / STORAGE" title={t.storage}><ResponsiveContainer width="100%" height={300}><LineChart data={storageCapacity}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis tickFormatter={(value) => compact(value, lang)} {...axis} width={58}/><Tooltip contentStyle={tip} labelFormatter={(value) => month(value, lang)} formatter={(value: number, name: string) => { const meta = Object.values(STORAGE).find((item) => item.key === name); return [`${formatInteger(Number(value), lang)} MW`, meta?.[lang] ?? name]; }}/>{Object.values(STORAGE).map((item) => <Line key={item.key} dataKey={item.key} name={item.key} stroke={item.color} dot={false} strokeWidth={2.2}/>)}</LineChart></ResponsiveContainer></Panel><Panel code="03 / CO₂-EQ" title={t.carbon}><ResponsiveContainer width="100%" height={300}><LineChart data={carbon}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(value) => month(value, lang)} {...axis}/><YAxis domain={[0, 100]} {...axis} unit="%" width={58}/><Tooltip contentStyle={tip} labelFormatter={(value) => month(value, lang)} formatter={(value: number) => [`${new Intl.NumberFormat(locale(lang), { maximumFractionDigits: 1 }).format(Number(value))}%`, t.carbon]}/><Line dataKey="share" stroke="#E56857" dot={false} strokeWidth={2.5}/></LineChart></ResponsiveContainer><p className="chart-note">{t.carbonNote}</p></Panel></div></>}

      {section === "method" && <><Panel code="01 / SOURCES" title={t.dataSources}><div className="source-list">{data.sources.filter((source) => source.key !== "omie").map((source) => <a href={source.url} key={source.key}><span>{source.key.replace(/_/g, " ")}</span><small>{source.url.replace(/^https?:\/\//, "").split("/")[0]}</small><time>{source.last_update ? new Date(source.last_update).toLocaleDateString(locale(lang)) : "—"}</time></a>)}</div></Panel><Panel code="02 / METHOD" title={t.methodology}><div className="method-copy"><p>{t.methodGeography}</p><p>{t.methodMissing}</p></div></Panel></>}

      <footer className="site-footer"><a href="https://danielalmazan.com">{t.visitPortfolio}</a><span>{t.lastUpdate}: {new Date(data.generated_at).toLocaleDateString(locale(lang))}</span></footer>
    </main>
  </div>;
}
